### ISSUE TITLE
Pressing the volume keys or other function keys wakes up the device while it's in sleep mode, but the controller doesn't cause a wake-up. This can easily lead to accidental activation. I would like only the power key to be able to wake up the device.

### ISSUE THREAD

**Issue by ppouerct** [ShadowBlip/HandyGCCS#116]
Pressing the volume keys or other function keys wakes up the device while it's in sleep mode, but the controller doesn't cause a wake-up. This can easily lead to accidental activation. I would like only the power key to be able to wake up the device.

**Comment by pastaq** [comment]
This is likely related to the USB wake rules and isn't HandyGCCS specific. We'll discuss in your other thread
