### ISSUE TITLE
Handycon can't detect keyboard 2 on Ally

### ISSUE THREAD

**Issue by Janer1** [ShadowBlip/HandyGCCS#125]
Systemctl status handycon keeps giving me a log saying it's unable to be detected. Tested on both bios version 330 and 323. Using Bazzite

**Comment by pastaq** [comment]
I'm working on adding support for BIOS 330 as that update changes some pcie addresses. Did you disable the SD card reader in BIOS by chance? That can also change the pcie addresses.

**Comment by Janer1** [comment]
Nope never disabled the sd card reader

**Comment by philmmanjaro** [comment]
most likely fixed via: https://github.com/honjow/HandyGCCS/commit/6a5a2c868d9e696c9cd59d2a8a68e6b93535d455

**Comment by pastaq** [comment]
> most likely fixed via: [honjow@6a5a2c8](https://github.com/honjow/HandyGCCS/commit/6a5a2c868d9e696c9cd59d2a8a68e6b93535d455)

I disagree if the issue exists in BIOS 323.

**Comment by philmmanjaro** [comment]
@Janer1 which kernel was used and is [this patch](https://github.com/ChimeraOS/linux/commit/975eca4580a3a4fbdfe3b24ee6523bc5aa9f2c95) applied?
