### ISSUE TITLE
keyboard and/or x-box 360 controller not found

### ISSUE THREAD

**Issue by edvorg** [ShadowBlip/HandyGCCS#17]
hi, I'm getting this message in the logs on ayaneo retro power on latest holoiso and latest handycon. Is there something I'm missing in my setup?

**Comment by pastaq** [comment]
Did you try a reboot? Occasionally it fails to reset everything when it closes.

**Comment by edvorg** [comment]
Hello, reboot didn't work for me, but after submitting this issue I
installed xpad dkms module into my system and it helped. Maybe worth
considering adding a note in the readme?

**Comment by pastaq** [comment]
I wasn't aware that the xpad driver is not present in HoloISO, it used to be. I'll have to test this later to confirm, so I'll leave this open for now. Thanks for the info.
