### ISSUE TITLE
How to customize buttons with handygccs.conf

### ISSUE THREAD

**Issue by ghost573** [ShadowBlip/HandyGCCS#53]
What am I meant to write to customize the button?

`button2 = QAM`

How should I write `KEY_LEFTMETA`, `KEY_LEFTCTRL` and `KEY_ESC` to get it to apply and work?

**Comment by pastaq** [comment]
The .conf only supports key combos that exist in constants.py. To add an additional key combo open a PR adding it to constants.py and including it in the import in handycon.py
You will need to name the event EVENT_X where x is the intended functionality of the button, please keep them in alphabetical order. If it is a duplicate functionality with a different key combination required, add a number to the end (e.g. "OSK_2": EVENT_OSK_2, )

https://github.com/ShadowBlip/HandyGCCS/blob/c6a1607748450858847c38f8b391e3e051186bed/constants.py#L194
https://github.com/ShadowBlip/HandyGCCS/blob/c6a1607748450858847c38f8b391e3e051186bed/handycon.py#L20
https://github.com/ShadowBlip/HandyGCCS/blob/c6a1607748450858847c38f8b391e3e051186bed/handycon.py#L52
