### ISSUE TITLE
Guide button on some Aya Neo devices stops working during use

### ISSUE THREAD

**Issue by pastaq** [ShadowBlip/HandyGCCS#55]
per https://github.com/ChimeraOS/chimeraos/issues/386

**Comment by aarron-lee** [comment]
Video of the issue: https://youtu.be/wre7ai3locI

Note that after pressing the Quick Access Menu (QAM) button, a mouse cursor appeared on the screen and started moving upward. You can see the mouse cursor in the video on the top-middle of the screen. This also sometimes happens for the Aya/Home button as well.

Once the mouse cursor disappears, the home button started working again.

Note, in the video I have LC mapped to `CTRL + 1`, which opens the home menu while the gamepadui interface is open.

**Comment by pastaq** [comment]
It appears that the button event gets queued but not properly cleared at some point so it ignored subsequent presses. This helps narrow down the issue, thanks.
