### ISSUE TITLE
Gyro stutters

### ISSUE THREAD

**Issue by Alexmjacobs** [ShadowBlip/HandyGCCS#59]
Hope I am doing this right, very new to this.

Installed on latest Holoiso on Aya Neo founder (1st IGG batch).

Used “esc” to enable and the gyro controls and they barely register or stutter and act unexpectedly in conjunction with the stick.

Is there a way tune this by adjusting one of the config files?

Had Gyro working relatively well in windows with Handheld Companion.

thank you so much creating this - button mapping is great.

**Comment by pastaq** [comment]
Gyro could definitely use some work. There is a "gyro sensitivity" setting in the config file located at /etc/handygccs.conf that you can tweak. TBS I'm not an expert on the gyro stuff so I'm certainly looking for anyone who can improve on the current implementation.

**Comment by Alexmjacobs** [comment]
Thank you so much for the info! I’ll take a poke around with that .conf file and see if that helps.AlexOn Dec 10, 2022, at 21:13, Derek J. Clark ***@***.***> wrote:﻿
Gyro could definitely use some work. There is a "gyro sensitivity" setting in the config file located at /etc/handygccs.conf that you can tweak. TBS I'm not an expert on the gyro stuff so I'm certainly looking for anyone who can improve on the current implementation.

**Comment by Alexmjacobs** [comment]
> Gyro could definitely use some work. There is a "gyro sensitivity" setting in the config file located at /etc/handygccs.conf that you can tweak. TBS I'm not an expert on the gyro stuff so I'm certainly looking for anyone who can improve on the current implementation.

**Comment by Alexmjacobs** [comment]
I did try sensitivity at 60 but had the same stuttering issues - Let me know if I can provide any more info.

Thanks.

**Comment by pastaq** [comment]
I made a change that should improve gyro response. I was doing something that caused an unexpected delay for gyro but was necessary for other events. That has now been bypassed for gyro events. Latest AUR release includes the change. It will be present in the next ChimeraOS version.

**Comment by Alexmjacobs** [comment]
Thank you much! Had gone back to windows, looking forward to giving this a try! Thank you for the update.Sent from my iPhoneOn Jan 11, 2023, at 01:05, Derek J. Clark ***@***.***> wrote:﻿
I made a change that should improve gyro response. I was doing something that caused an unexpected delay for gyro but was necessary for other events. That has now been bypassed for gyro events. Latest AUR release includes the change. It will be present in the next ChimeraOS version.
