### ISSUE TITLE
Update 3.4 breaks Controllerfunction with HandyGCCS on Aya Neo Air

### ISSUE THREAD

**Issue by Nik123456789010** [ShadowBlip/HandyGCCS#64]
Holoiso update itself to 3.4. Is there a fix, or a possibility to disable Steam Deck Updates?

**Comment by Samsagax** [comment]
Hello! @Nik123456789010 Can you provide some logs from handycon? How exactly does it break? As for the question. You should ask HoloISO develpers.

**Comment by Samsagax** [comment]
try with:
`$ sudo journalctl --unit handycon`

**Comment by Nik123456789010** [comment]
ng@holoiso ~)$ sudo journalctl ––unit handycon
Failed to add match '––unit': Invalid argument
(1)(ng@holoiso ~)$ sudo journalctl ––unit handyc
Failed to add match '––unit': Invalid argument
(1)(ng@holoiso ~)$
(1)(ng@holoiso ~)$ sudo journalctl --unit handycon
Dec 15 14:53:15 holoiso systemd[1]: Stopping Handheld Game Console Controller Service...
Dec 15 14:53:15 holoiso python3[522]: [221215_14:53:15 | handycon.py:1030:restore_all] Receved exit signal. R>
Dec 15 14:53:15 holoiso python3[522]: [221215_14:53:15 | handycon.py:1050:restore_all] Devices restored.
Dec 15 14:53:15 holoiso python3[522]: [221215_14:53:15 | handycon.py:1060:restore_all] Handheld Game Console >
Dec 15 14:53:16 holoiso systemd[1]: handycon.service: Deactivated successfully.
Dec 15 14:53:16 holoiso systemd[1]: Stopped Handheld Game Console Controller Service.
Dec 15 14:53:16 holoiso systemd[1]: handycon.service: Consumed 8.840s CPU time.
-- Boot 203c5383541f4aaeabe1c1a5bca6b300 --
Dec 15 22:31:55 holoiso systemd[1]: Started Handheld Game Console Controller Service.
Dec 15 22:31:55 holoiso python3[529]: [221215_22:31:55 | handycon.py:248:id_system] Identified host system as>
Dec 15 22:31:55 holoiso python3[529]: [221215_22:31:55 | handycon.py:260:get_config] Loading existing config:>
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:1088:main] Handheld Game Console Control>
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:833:capture_controller_events] Attemptin>
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:346:get_controller] Controller device no>
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:439:get_gyro] Found gyro device. Gyro su>
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:782:capture_keyboard_events] Attempting >
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:385:get_keyboard] Found AT Translated Se>
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:905:capture_power_events] Attempting to >
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:422:get_powerkey] Found Power Button. Ca>
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:833:capture_controller_events] Attemptin>
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:346:get_controller] Controller device no>
Dec 15 22:31:57 holoiso python3[529]: [221215_22:31:57 | handycon.py:833:capture_controller_events] Attemptin>
Dec 15 22:31:57 holoiso python3[529]: [221215_22:31:57 | handycon.py:346:get_controller] Controller device no>
Dec 15 22:31:57 holoiso python3[529]: [221215_22:31:57 | handycon.py:833:capture_controller_events] Attemptin>
Dec 15 22:31:57 holoiso python3[529]: [221215_22:31:57 | handycon.py:346:get_controller] Controller device no>
Dec 15 22:31:58 holoiso python3[529]: [221215_22:31:58 | handycon.py:833:capture_controller_events] Attemptin>
Dec 15 22:31:58 holoiso python3[529]: [221215_22:31:58 | handycon.py:346:get_controller] Controller device no>
lines 1-27...skipping...
Dec 15 14:53:15 holoiso systemd[1]: Stopping Handheld Game Console Controller Service...
Dec 15 14:53:15 holoiso python3[522]: [221215_14:53:15 | handycon.py:1030:restore_all] Receved exit signal. Restoring devices.
Dec 15 14:53:15 holoiso python3[522]: [221215_14:53:15 | handycon.py:1050:restore_all] Devices restored.
Dec 15 14:53:15 holoiso python3[522]: [221215_14:53:15 | handycon.py:1060:restore_all] Handheld Game Console Controller Service stopped.
Dec 15 14:53:16 holoiso systemd[1]: handycon.service: Deactivated successfully.
Dec 15 14:53:16 holoiso systemd[1]: Stopped Handheld Game Console Controller Service.
Dec 15 14:53:16 holoiso systemd[1]: handycon.service: Consumed 8.840s CPU time.
-- Boot 203c5383541f4aaeabe1c1a5bca6b300 --
Dec 15 22:31:55 holoiso systemd[1]: Started Handheld Game Console Controller Service.
Dec 15 22:31:55 holoiso python3[529]: [221215_22:31:55 | handycon.py:248:id_system] Identified host system as AIR and configured defaults for AYA_GEN2.
Dec 15 22:31:55 holoiso python3[529]: [221215_22:31:55 | handycon.py:260:get_config] Loading existing config: /etc/handygccs/handygccs.conf
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:1088:main] Handheld Game Console Controller Service started.
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:439:get_gyro] Found gyro device. Gyro support enabled.
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:782:capture_keyboard_events] Attempting to grab keyboard device...
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:385:get_keyboard] Found AT Translated Set 2 keyboard. Capturing input data.
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:905:capture_power_events] Attempting to grab power device...
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:422:get_powerkey] Found Power Button. Capturing input data.
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:31:56 holoiso python3[529]: [221215_22:31:56 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:31:57 holoiso python3[529]: [221215_22:31:57 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:31:57 holoiso python3[529]: [221215_22:31:57 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:31:57 holoiso python3[529]: [221215_22:31:57 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:31:57 holoiso python3[529]: [221215_22:31:57 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:31:58 holoiso python3[529]: [221215_22:31:58 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:31:58 holoiso python3[529]: [221215_22:31:58 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:31:58 holoiso python3[529]: [221215_22:31:58 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:31:58 holoiso python3[529]: [221215_22:31:58 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:31:59 holoiso python3[529]: [221215_22:31:59 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:31:59 holoiso python3[529]: [221215_22:31:59 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:31:59 holoiso python3[529]: [221215_22:31:59 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:31:59 holoiso python3[529]: [221215_22:31:59 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:00 holoiso python3[529]: [221215_22:32:00 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:32:00 holoiso python3[529]: [221215_22:32:00 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:00 holoiso python3[529]: [221215_22:32:00 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:32:00 holoiso python3[529]: [221215_22:32:00 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:01 holoiso python3[529]: [221215_22:32:01 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:32:01 holoiso python3[529]: [221215_22:32:01 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:01 holoiso python3[529]: [221215_22:32:01 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:32:01 holoiso python3[529]: [221215_22:32:01 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:02 holoiso python3[529]: [221215_22:32:02 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:32:02 holoiso python3[529]: [221215_22:32:02 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:02 holoiso python3[529]: [221215_22:32:02 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:32:02 holoiso python3[529]: [221215_22:32:02 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:03 holoiso python3[529]: [221215_22:32:03 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:32:03 holoiso python3[529]: [221215_22:32:03 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:03 holoiso python3[529]: [221215_22:32:03 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:32:03 holoiso python3[529]: [221215_22:32:03 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:04 holoiso python3[529]: [221215_22:32:04 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
Dec 15 22:32:04 holoiso python3[529]: [221215_22:32:04 | handycon.py:346:get_controller] Controller device not yet found. Restarting scan.
Dec 15 22:32:04 holoiso python3[529]: [221215_22:32:04 | handycon.py:833:capture_controller_events] Attempting to grab controller device...
lines 1-52

**Comment by pastaq** [comment]
I think I need to add a check for the old file structure to remove them. Seems to be causing conflicts on upgrade.
Disable handycon service
`sudo systemctl disable --now handcon`
Delete the old systemd unit
`sudo rm /etc/systemd/system/handycon.service`
Reenable handy con
`sudo systemctl enable --now handcon`

**Comment by Nik123456789010** [comment]
Thank you, but have no luck with this. The Update 3.3.3, 3.4 break even more on the Aya, there is what like later Firmware update für the Steam Deck

**Comment by pastaq** [comment]
Its difficult to assist without more feedback than it didn't work. Are there any specific errors you received when running those commands or change in specific behavior/symptoms? 

Lets see if your devices are properly being detected.

`sudo systemctl disable --now handcon`
`sudo reboot`
`sudo pacman -Sy evtest`
`sudo evtest`
select the item `Microsoft X-Box 360 pad` and verify the normal xbox360 buttons all work
ctrl+c to quit
select the item `AT Translated Set 2 keyboard` and verify the two face buttons work, as well as the RC and LC buttons on top (they are difficult to see, but if you look top down they are next to the shoulder buttons but closer to the center)


let me know if all those are being detected and all events exist while handygccs is off

**Comment by luisho24** [comment]
Hello, 

I also have issues with Handycon on my Ayaneo Air Pro.  I follow your instructions, however, I do not even see "Microsoft X-Box 360 pad".  Only AT TRanslated Set 2 keyboard.  

The only keys it captures are the Ayaneo special keys. But non of the other controller keys actually work. 

$ sudo evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      Lid Switch
/dev/input/event1:      Power Button
/dev/input/event2:      Power Button
/dev/input/event3:      AT Translated Set 2 keyboard
/dev/input/event4:      Video Bus
/dev/input/event5:      Goodix Capacitive TouchScreen
/dev/input/event6:      PC Speaker
/dev/input/event7:      HD-Audio Generic HDMI/DP,pcm=3
/dev/input/event8:      HD-Audio Generic HDMI/DP,pcm=7
/dev/input/event9:      HD-Audio Generic Mic
/dev/input/event10:     HD-Audio Generic Headphone
Select the device event number [0-10]: 3
Input driver version is 1.0.1
Input device ID: bus 0x11 vendor 0x1 product 0x1 version 0xab83
Input device name: "AT Translated Set 2 keyboard"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 1 (KEY_ESC)
    Event code 2 (KEY_1)
    Event code 3 (KEY_2)
    Event code 4 (KEY_3)
    Event code 5 (KEY_4)
    Event code 6 (KEY_5)
    Event code 7 (KEY_6)
    Event code 8 (KEY_7)
    Event code 9 (KEY_8)
    Event code 10 (KEY_9)
    Event code 11 (KEY_0)
    Event code 12 (KEY_MINUS)
    Event code 13 (KEY_EQUAL)
    Event code 14 (KEY_BACKSPACE)
    Event code 15 (KEY_TAB)
    Event code 16 (KEY_Q)
    Event code 17 (KEY_W)
    Event code 18 (KEY_E)
    Event code 19 (KEY_R)
    Event code 20 (KEY_T)
    Event code 21 (KEY_Y)
    Event code 22 (KEY_U)
    Event code 23 (KEY_I)
    Event code 24 (KEY_O)
    Event code 25 (KEY_P)
    Event code 26 (KEY_LEFTBRACE)
    Event code 27 (KEY_RIGHTBRACE)
    Event code 28 (KEY_ENTER)
    Event code 29 (KEY_LEFTCTRL)
    Event code 30 (KEY_A)
    Event code 31 (KEY_S)
    Event code 32 (KEY_D)
    Event code 33 (KEY_F)
    Event code 34 (KEY_G)
    Event code 35 (KEY_H)
    Event code 36 (KEY_J)
    Event code 37 (KEY_K)
    Event code 38 (KEY_L)
    Event code 39 (KEY_SEMICOLON)
    Event code 40 (KEY_APOSTROPHE)
    Event code 41 (KEY_GRAVE)
    Event code 42 (KEY_LEFTSHIFT)
    Event code 43 (KEY_BACKSLASH)
    Event code 44 (KEY_Z)
    Event code 45 (KEY_X)
    Event code 46 (KEY_C)
    Event code 47 (KEY_V)
    Event code 48 (KEY_B)
    Event code 49 (KEY_N)
    Event code 50 (KEY_M)
    Event code 51 (KEY_COMMA)
    Event code 52 (KEY_DOT)
    Event code 53 (KEY_SLASH)
    Event code 54 (KEY_RIGHTSHIFT)
    Event code 55 (KEY_KPASTERISK)
    Event code 56 (KEY_LEFTALT)
    Event code 57 (KEY_SPACE)
    Event code 58 (KEY_CAPSLOCK)
    Event code 59 (KEY_F1)
    Event code 60 (KEY_F2)
    Event code 61 (KEY_F3)
    Event code 62 (KEY_F4)
    Event code 63 (KEY_F5)
    Event code 64 (KEY_F6)
    Event code 65 (KEY_F7)
    Event code 66 (KEY_F8)
    Event code 67 (KEY_F9)
    Event code 68 (KEY_F10)
    Event code 69 (KEY_NUMLOCK)
    Event code 70 (KEY_SCROLLLOCK)
    Event code 71 (KEY_KP7)
    Event code 72 (KEY_KP8)
    Event code 73 (KEY_KP9)
    Event code 74 (KEY_KPMINUS)
    Event code 75 (KEY_KP4)
    Event code 76 (KEY_KP5)
    Event code 77 (KEY_KP6)
    Event code 78 (KEY_KPPLUS)
    Event code 79 (KEY_KP1)
    Event code 80 (KEY_KP2)
    Event code 81 (KEY_KP3)
    Event code 82 (KEY_KP0)
    Event code 83 (KEY_KPDOT)
    Event code 85 (KEY_ZENKAKUHANKAKU)
    Event code 86 (KEY_102ND)
    Event code 87 (KEY_F11)
    Event code 88 (KEY_F12)
    Event code 89 (KEY_RO)
    Event code 90 (KEY_KATAKANA)
    Event code 91 (KEY_HIRAGANA)
    Event code 92 (KEY_HENKAN)
    Event code 93 (KEY_KATAKANAHIRAGANA)
    Event code 94 (KEY_MUHENKAN)
    Event code 95 (KEY_KPJPCOMMA)
    Event code 96 (KEY_KPENTER)
    Event code 97 (KEY_RIGHTCTRL)
    Event code 98 (KEY_KPSLASH)
    Event code 99 (KEY_SYSRQ)
    Event code 100 (KEY_RIGHTALT)
    Event code 102 (KEY_HOME)
    Event code 103 (KEY_UP)
    Event code 104 (KEY_PAGEUP)
    Event code 105 (KEY_LEFT)
    Event code 106 (KEY_RIGHT)
    Event code 107 (KEY_END)
    Event code 108 (KEY_DOWN)
    Event code 109 (KEY_PAGEDOWN)
    Event code 110 (KEY_INSERT)
    Event code 111 (KEY_DELETE)
    Event code 112 (KEY_MACRO)
    Event code 113 (KEY_MUTE)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 116 (KEY_POWER)
    Event code 117 (KEY_KPEQUAL)
    Event code 118 (KEY_KPPLUSMINUS)
    Event code 119 (KEY_PAUSE)
    Event code 121 (KEY_KPCOMMA)
    Event code 122 (KEY_HANGUEL)
    Event code 123 (KEY_HANJA)
    Event code 124 (KEY_YEN)
    Event code 125 (KEY_LEFTMETA)
    Event code 126 (KEY_RIGHTMETA)
    Event code 127 (KEY_COMPOSE)
    Event code 128 (KEY_STOP)
    Event code 140 (KEY_CALC)
    Event code 142 (KEY_SLEEP)
    Event code 143 (KEY_WAKEUP)
    Event code 155 (KEY_MAIL)
    Event code 156 (KEY_BOOKMARKS)
    Event code 157 (KEY_COMPUTER)
    Event code 158 (KEY_BACK)
    Event code 159 (KEY_FORWARD)
    Event code 163 (KEY_NEXTSONG)
    Event code 164 (KEY_PLAYPAUSE)
    Event code 165 (KEY_PREVIOUSSONG)
    Event code 166 (KEY_STOPCD)
    Event code 172 (KEY_HOMEPAGE)
    Event code 173 (KEY_REFRESH)
    Event code 183 (KEY_F13)
    Event code 184 (KEY_F14)
    Event code 185 (KEY_F15)
    Event code 217 (KEY_SEARCH)
    Event code 226 (KEY_MEDIA)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 17 (EV_LED)
    Event code 0 (LED_NUML) state 0
    Event code 1 (LED_CAPSL) state 0
    Event code 2 (LED_SCROLLL) state 0
Key repeat handling:
  Repeat type 20 (EV_REP)
    Repeat code 0 (REP_DELAY)
      Value    250
    Repeat code 1 (REP_PERIOD)
      Value     33
Properties:
Testing ... (interrupt to exit)
Event: time 1671379321.241130, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.241130, type 1 (EV_KEY), code 97 (KEY_RIGHTCTRL), value 1
Event: time 1671379321.241130, -------------- SYN_REPORT ------------
Event: time 1671379321.247483, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.247483, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 1
Event: time 1671379321.247483, -------------- SYN_REPORT ------------
Event: time 1671379321.250153, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.250153, type 1 (EV_KEY), code 88 (KEY_F12), value 1
Event: time 1671379321.250153, -------------- SYN_REPORT ------------
Event: time 1671379321.366887, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.366887, type 1 (EV_KEY), code 88 (KEY_F12), value 0
Event: time 1671379321.366887, -------------- SYN_REPORT ------------
Event: time 1671379321.376454, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.376454, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 0
Event: time 1671379321.376454, -------------- SYN_REPORT ------------
Event: time 1671379321.389280, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.389280, type 1 (EV_KEY), code 97 (KEY_RIGHTCTRL), value 0
Event: time 1671379321.389280, -------------- SYN_REPORT ------------
Event: time 1671379321.395309, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.395309, -------------- SYN_REPORT ------------
Event: time 1671379321.404337, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.404337, -------------- SYN_REPORT ------------
Event: time 1671379321.413614, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.413614, -------------- SYN_REPORT ------------
Event: time 1671379321.419331, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.419331, -------------- SYN_REPORT ------------
Event: time 1671379321.428422, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.428422, -------------- SYN_REPORT ------------
Event: time 1671379321.437311, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.437311, -------------- SYN_REPORT ------------
Event: time 1671379321.443404, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.443404, -------------- SYN_REPORT ------------
Event: time 1671379321.452356, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.452356, -------------- SYN_REPORT ------------
Event: time 1671379321.461279, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.461279, -------------- SYN_REPORT ------------
Event: time 1671379321.468278, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.468278, -------------- SYN_REPORT ------------
Event: time 1671379321.478347, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.478347, -------------- SYN_REPORT ------------
Event: time 1671379321.487309, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.487309, -------------- SYN_REPORT ------------
Event: time 1671379321.496381, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.496381, -------------- SYN_REPORT ------------
Event: time 1671379321.505435, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.505435, -------------- SYN_REPORT ------------
Event: time 1671379321.514394, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.514394, -------------- SYN_REPORT ------------
Event: time 1671379321.520489, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.520489, -------------- SYN_REPORT ------------
Event: time 1671379321.529403, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.529403, -------------- SYN_REPORT ------------
Event: time 1671379321.542375, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.542375, -------------- SYN_REPORT ------------
Event: time 1671379321.548397, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.548397, -------------- SYN_REPORT ------------
Event: time 1671379321.557442, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.557442, -------------- SYN_REPORT ------------
Event: time 1671379321.566486, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.566486, -------------- SYN_REPORT ------------
Event: time 1671379321.572380, type 4 (EV_MSC), code 4 (MSC_SCAN), value 58
Event: time 1671379321.572380, -------------- SYN_REPORT ------------
Event: time 1671379321.581490, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379321.581490, -------------- SYN_REPORT ------------
Event: time 1671379321.590397, type 4 (EV_MSC), code 4 (MSC_SCAN), value 9d
Event: time 1671379321.590397, -------------- SYN_REPORT ------------
Event: time 1671379330.581967, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.581967, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 1
Event: time 1671379330.581967, -------------- SYN_REPORT ------------
Event: time 1671379330.584956, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.584956, type 1 (EV_KEY), code 32 (KEY_D), value 1
Event: time 1671379330.584956, -------------- SYN_REPORT ------------
Event: time 1671379330.686298, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.686298, type 1 (EV_KEY), code 125 (KEY_LEFTMETA), value 0
Event: time 1671379330.686298, -------------- SYN_REPORT ------------
Event: time 1671379330.692005, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.692005, type 1 (EV_KEY), code 32 (KEY_D), value 0
Event: time 1671379330.692005, -------------- SYN_REPORT ------------
Event: time 1671379330.701013, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.701013, -------------- SYN_REPORT ------------
Event: time 1671379330.706962, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.706962, -------------- SYN_REPORT ------------
Event: time 1671379330.716052, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.716052, -------------- SYN_REPORT ------------
Event: time 1671379330.721989, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.721989, -------------- SYN_REPORT ------------
Event: time 1671379330.731058, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.731058, -------------- SYN_REPORT ------------
Event: time 1671379330.737198, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.737198, -------------- SYN_REPORT ------------
Event: time 1671379330.746440, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.746440, -------------- SYN_REPORT ------------
Event: time 1671379330.752018, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.752018, -------------- SYN_REPORT ------------
Event: time 1671379330.761836, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.761836, -------------- SYN_REPORT ------------
Event: time 1671379330.768011, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.768011, -------------- SYN_REPORT ------------
Event: time 1671379330.777487, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.777487, -------------- SYN_REPORT ------------
Event: time 1671379330.783032, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.783032, -------------- SYN_REPORT ------------
Event: time 1671379330.792074, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.792074, -------------- SYN_REPORT ------------
Event: time 1671379330.798023, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.798023, -------------- SYN_REPORT ------------
Event: time 1671379330.807079, type 4 (EV_MSC), code 4 (MSC_SCAN), value db
Event: time 1671379330.807079, -------------- SYN_REPORT ------------
Event: time 1671379330.813048, type 4 (EV_MSC), code 4 (MSC_SCAN), value 20
Event: time 1671379330.813048, -------------- SYN_REPORT ------------

**Comment by pastaq** [comment]
@luisho24 

Hmmm, that would indicate that the xpad driver isn't loading the xb360 controller device initially. This should be reported on the HoloISO issues tracker. Nothing HandyGCCS does would preclude that device from initializing. I don't know if they changed anything over there recently, but the driver loads properly for me in ChimeraOS.

**Comment by Nik123456789010** [comment]
Sorry, about my 2 Installation i recognize^it yet: different startoptions( not set by me): Steamdeck, and linux-holoiso  and there HandyGCCS is working. So yes, for me its a chase für HoloISO. Thank you!
