### ISSUE TITLE
I can’t install HandyGCCS

### ISSUE THREAD

**Issue by McWalters00** [ShadowBlip/HandyGCCS#66]
When I put the command in « Console » it puts that on me.
![image](https://user-images.githubusercontent.com/96343387/209818539-70f2eca9-4712-4d0c-8997-9b285917bb22.jpeg)

**Comment by ruineka** [comment]
Holoiso has broken steam repo configurations. You'll have to work around this.

Enter this in the console in desktop mode:

`git clone https://github.com/ShadowBlip/HandyGCCS.git
cd ~/HandyGCCS
sudo cp -Rv usr/* /usr
sudo udevadm control -R
sudo systemctl enable handycon && sudo systemctl start handycon`

**Comment by pastaq** [comment]
> Holoiso has broken steam repo configurations. You'll have to work around this.
> 
> Enter this in the console in desktop mode:
> 
> `git clone https://github.com/ShadowBlip/HandyGCCS.git cd ~/HandyGCCS sudo cp -Rv usr/* /usr sudo udevadm control -R sudo systemctl enable handycon && sudo systemctl start handycon`

That will install the scripts but not the dependencies. There currently isn't a way that will get the necessary libraries to install otherwise.
@McWalters00 HoloISO is broken and currently not supported.

**Comment by McWalters00** [comment]
> > Holoiso has broken steam repo configurations. You'll have to work around this.
> 
> > 
> 
> > Enter this in the console in desktop mode:
> 
> > 
> 
> > `git clone https://github.com/ShadowBlip/HandyGCCS.git cd ~/HandyGCCS sudo cp -Rv usr/* /usr sudo udevadm control -R sudo systemctl enable handycon && sudo systemctl start handycon`
> 
> 
> 
> That will install the scripts but not the dependencies. There currently isn't a way that will get the necessary libraries to install otherwise.
> 
> @McWalters00 HoloISO is broken and currently not supported. 

How is it that nothing works on holoiso when it worked a few months ago?

**Comment by ruineka** [comment]
> > Holoiso has broken steam repo configurations. You'll have to work around this.
> > 
> > Enter this in the console in desktop mode:
> > 
> > `git clone https://github.com/ShadowBlip/HandyGCCS.git cd ~/HandyGCCS sudo cp -Rv usr/* /usr sudo udevadm control -R sudo systemctl enable handycon && sudo systemctl start handycon`
> 
> That will install the scripts but not the dependencies. There currently isn't a way that will get the necessary libraries to install otherwise.
> @McWalters00 HoloISO is broken and currently not supported. 

The dependencies are on Holoiso to begin with so this method works at this current time. It bypasses the fact Holoiso has the broken databases at the moment.

**Comment by ruineka** [comment]
> > > Holoiso has broken steam repo configurations. You'll have to work around this.
> > 
> > > 
> > 
> > > Enter this in the console in desktop mode:
> > 
> > > 
> > 
> > > `git clone https://github.com/ShadowBlip/HandyGCCS.git cd ~/HandyGCCS sudo cp -Rv usr/* /usr sudo udevadm control -R sudo systemctl enable handycon && sudo systemctl start handycon`
> > 
> > 
> > 
> > That will install the scripts but not the dependencies. There currently isn't a way that will get the necessary libraries to install otherwise.
> > 
> > @McWalters00 HoloISO is broken and currently not supported. 
> 
> How is it that nothing works on holoiso when it worked a few months ago?

Valve changed their repos which Holoiso directly pulls from so the database is invalid and needs to be updated to match Valves changes.

**Comment by McWalters00** [comment]
> > > > Holoiso has broken steam repo configurations. You'll have to work around this.
> > > 
> > > > 
> > > 
> > > > Enter this in the console in desktop mode:
> > > 
> > > > 
> > > 
> > > > `git clone https://github.com/ShadowBlip/HandyGCCS.git cd ~/HandyGCCS sudo cp -Rv usr/* /usr sudo udevadm control -R sudo systemctl enable handycon && sudo systemctl start handycon`
> > > 
> > > 
> > > 
> > > That will install the scripts but not the dependencies. There currently isn't a way that will get the necessary libraries to install otherwise.
> > > 
> > > @McWalters00 HoloISO is broken and currently not supported. 
> > 
> > How is it that nothing works on holoiso when it worked a few months ago?
> 
> Valve changed their repos which Holoiso directly pulls from so the database is invalid and needs to be updated to match Valves changes. 

And if I go to chimera OS I would have the same problems?

**Comment by pastaq** [comment]
> same problems?

No, we don't see the valve repository in our system image.
