### ISSUE TITLE
AIR - Failed to load - result exit-code

### ISSUE THREAD

**Issue by soreySr** [ShadowBlip/HandyGCCS#70]
This is on a fresh install of ChimeraOS on an Aya Neo Air 512gb 5560u model. HandyGCCS never starts, always gives an error when viewed in the console (see picture.)

![6A173220-C260-4C10-854D-61AD5315195E](https://user-images.githubusercontent.com/123104680/213511309-dd875c30-6802-4b8f-925f-ebfd96b87f7e.jpeg)

**Comment by soreySr** [comment]
Submitted at the request of Pastaq

**Comment by pastaq** [comment]
can you provide the output of `cat /etc/handygccs/handygccs.conf` please?

**Comment by pastaq** [comment]
Is this still happening?
