### ISSUE TITLE
Unresponsive Controller

### ISSUE THREAD

**Issue by Sqedlleshimers** [ShadowBlip/HandyGCCS#75]
[gamer chimeraos journalctl.txt](https://github.com/ShadowBlip/HandyGCCS/files/10820289/gamer.chimeraos.journalctl.txt)

Device:
AOKZOE A1

Issues:
Built in controller starts to wig out. Input is delayed and only reconized when the key/joysticks/buttons are held. Once they are held the controller goes unresponsive. Almost like stickey keys where the keys aren't pressed but the previous input is sustained.

Solution:
Disabling the "Handycon" service fixes the controller unresponsiveness issue. But the sustained input continues.

Attached the history of the service as well.

**Comment by pastaq** [comment]
Os this still an issue?
