### ISSUE TITLE
ASUSTek ROG Ally RC71L (2023)

### ISSUE THREAD

**Issue by philmmanjaro** [ShadowBlip/HandyGCCS#93]
Since the initial "Aprils Fools Day" a lot of "drama" is happening around ASUS and their gaming handheld. I was able to boot a current [Gnome daily build](https://github.com/manjaro-gnome/download/releases/tag/202306130251) by going thru some hoops. Now that version is on a USB-C Stick installed so I can experiment with the device.

## What works

- Xbox 360 controllers including **select** and **start** buttons
- External Monitor, Network, USB-C, USB2/3 via dock
- microSD card reader (not bootable, though)

## Not tested yet
- Headphone jack
- VRR settings

## What doesn't work yet
- Settings overlay button (N-key / asus-wmi)
- Armoury Crate button (N-key / asus-wmi)
- both buttons on the back (N-keys / asus-wmi)
- Audio via speakers
- Wifi (maybe [fixed](https://gitlab.manjaro.org/packages/core/linux63/-/commit/88bc7af4dfde0e8afb9fbc9a7f4d3ac8aa2905de))

A current **probe** can be found [here](https://linux-hardware.org/?probe=38138ba23d)

Would be nice to see some support for the missing buttons.

**Comment by pastaq** [comment]
Most of these issues aren't related to HandyGCCS. Once the asus_wmi driver has support for the keys we can add support for the special buttons. Everything else we need to fix through another avenue.
