### ISSUE TITLE
Add additional event type to configuration

### ISSUE THREAD

**Issue by tcdude** [ShadowBlip/HandyGCCS#99]
It would be nice to have the possibility of custom events that allow the user to configure HandyGCCS to launch commands/scripts through button presses.

I imagine that there could be a custom event called `USR` (or similar), which also expects a command on the same config line.

Something along the lines of this: `button1=USR,"/path/to/my/executable arg1 arg2..."`

**Comment by pastaq** [comment]
I've decided not to do this. The service is running as root and allowing arbitrary code execution as the root user from a single button press seems like a really bad idea.
